const types = {
  BLE_MANAGER: 'BLE_MANAGER',
  BLE_SET_SCAN_TIME: 'BLE_SET_SCAN_TIME',
  BLE_CONNECTED_DEVICE: 'BLE_CONNECTED_DEVICE',
  BLE_CONNECTED_DEVICE_ID: 'BLE_CONNECTED_DEVICE_ID',
  BLE_SERVICE_UUIDS: 'BLE_SERVICE_UUIDS',
  BLE_CHARACTERISTICS_UUID: 'BLE_CHARACTERISTICS_UUID',
};

export default types;